apiVersion: 1

datasources:
- name: prometheus
  type: prometheus
  access: direct
  # Note Grafana will do calls from the frontend! So don't change this to the docker host name!
  url: http://localhost:9090
  isDefault: true